# canonical name -> aliases (all matched case-insensitively on word boundaries)
VOCAB: dict[str, list[str]] = {
    # languages
    "python": [],
    "javascript": ["js"],
    "typescript": ["ts"],
    "java": [],
    "kotlin": [],
    "go": ["golang"],
    "rust": [],
    "c++": ["cpp"],
    "c#": ["csharp"],
    ".net": ["dotnet", "asp.net"],
    "php": [],
    "ruby": [],
    "scala": [],
    "swift": [],
    "sql": [],
    "bash": ["shell scripting"],
    # python ecosystem
    "django": [],
    "flask": [],
    "fastapi": [],
    "aiohttp": [],
    "celery": [],
    "sqlalchemy": [],
    "pydantic": [],
    "pytest": [],
    "asyncio": [],
    "pandas": [],
    "numpy": [],
    # web
    "react": ["reactjs", "react.js"],
    "vue": ["vue.js", "vuejs"],
    "angular": [],
    "node.js": ["nodejs", "node"],
    "next.js": ["nextjs"],
    "graphql": [],
    "rest": ["restful"],
    "grpc": [],
    "websockets": [],
    # data / storage
    "postgresql": ["postgres"],
    "mysql": [],
    "mongodb": ["mongo"],
    "redis": [],
    "elasticsearch": ["opensearch"],
    "kafka": [],
    "rabbitmq": [],
    "sqlite": [],
    "clickhouse": [],
    "snowflake": [],
    "bigquery": [],
    "airflow": [],
    "spark": ["pyspark"],
    "dbt": [],
    "etl": [],
    # devops / cloud
    "docker": [],
    "kubernetes": ["k8s"],
    "aws": ["amazon web services"],
    "gcp": ["google cloud"],
    "azure": [],
    "terraform": [],
    "ansible": [],
    "linux": [],
    "ci/cd": ["cicd", "github actions", "gitlab ci", "jenkins"],
    "git": [],
    "prometheus": [],
    "grafana": [],
    "microservices": ["microservice"],
    # ai / ml
    "machine learning": ["ml"],
    "deep learning": [],
    "nlp": ["natural language processing"],
    "llm": ["llms", "large language models", "large language model"],
    "generative ai": ["genai", "gen ai", "generative-ai"],
    "ai": ["artificial intelligence"],
    "rag": ["retrieval augmented generation", "retrieval-augmented generation"],
    "langchain": [],
    "llamaindex": [],
    "openai": [],
    "anthropic": [],
    "mcp": [],
    "prompt engineering": [],
    "pytorch": [],
    "tensorflow": [],
    "scikit-learn": ["sklearn"],
    "hugging face": ["huggingface"],
    "computer vision": [],
    "vector database": ["vector db", "pgvector", "pinecone", "qdrant", "weaviate", "chroma"],
    "mlops": [],
    # qa / misc
    "tdd": [],
    "agile": ["scrum"],
    "selenium": [],
    "playwright": [],
}

# Common English words: only match these through unambiguous phrases, never the bare word.
SEARCH_TERMS_OVERRIDE: dict[str, list[str]] = {
    "go": ["golang", "go developer", "go engineer", "go (golang)"],
    "rest": ["rest api", "rest apis", "restful", "rest/graphql"],
    "spark": ["apache spark", "pyspark"],
    "agile": ["agile", "scrum"],
}

# Having any of the key skills implies the broader umbrella skill.
IMPLIES: dict[str, set[str]] = {
    "ai": {
        "llm",
        "rag",
        "generative ai",
        "nlp",
        "deep learning",
        "pytorch",
        "tensorflow",
        "langchain",
        "llamaindex",
        "openai",
        "anthropic",
        "mcp",
        "prompt engineering",
        "computer vision",
        "machine learning",
        "hugging face",
        "vector database",
    },
    "machine learning": {
        "deep learning",
        "pytorch",
        "tensorflow",
        "scikit-learn",
        "nlp",
        "computer vision",
        "mlops",
    },
    "generative ai": {"llm", "rag", "langchain", "llamaindex", "prompt engineering"},
    "sql": {"postgresql", "mysql", "sqlite", "clickhouse", "bigquery", "snowflake"},
    "rest": {"fastapi", "django", "flask"},
}

ALIAS_TO_CANON: dict[str, str] = {
    alias: canon for canon, aliases in VOCAB.items() for alias in (canon, *aliases)
}
